/****** Object:  Table [dbo].[BlogPostTags]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[BlogPostTags](
	[BlogPostID] [int] NOT NULL,
	[TagID] [int] NOT NULL,
 CONSTRAINT [PK_BlogPostTags] PRIMARY KEY CLUSTERED 
(
	[BlogPostID] ASC,
	[TagID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_BlogPostTags_TagID] ON [dbo].[BlogPostTags]
(
	[TagID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
ALTER TABLE [dbo].[BlogPostTags]  WITH CHECK ADD  CONSTRAINT [FK_BlogPostTags_BlogPosts_BlogPostID] FOREIGN KEY([BlogPostID])
REFERENCES [dbo].[BlogPosts] ([BlogPostID])
ON DELETE CASCADE
ALTER TABLE [dbo].[BlogPostTags] CHECK CONSTRAINT [FK_BlogPostTags_BlogPosts_BlogPostID]
ALTER TABLE [dbo].[BlogPostTags]  WITH CHECK ADD  CONSTRAINT [FK_BlogPostTags_Tags_TagID] FOREIGN KEY([TagID])
REFERENCES [dbo].[Tags] ([TagID])
ON DELETE CASCADE
ALTER TABLE [dbo].[BlogPostTags] CHECK CONSTRAINT [FK_BlogPostTags_Tags_TagID]
